---
driver:
  name: vagrant
  customize:
    memory: 512
    cpus: 1
  network:
    - ['private_network', {ip: '10.0.0.2'}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[dokku::install]
      - recipe[dokku::test_helper]
    attributes:
      dokku:
        domain: <%= ENV['DOKKU_DOMAIN'] || '10.0.0.2.xip.io' %>
        test_deploy: 
          apps:
            - 'python-flask'
